package com.execeptionalhandling;

public class Data2 {

	public static void main(String[] args) {
		
		System.out.println("hi");
		System.out.println("hello");
		
		//1) A scenario where ArithmeticException occurs.
		/*try{
			int a = 10/0;
		}catch(Exception e) {
			System.out.println(e);
		}*/
		

		//1) A scenario where ArithmeticException occurs.
		/*try{
			int a = 10/0;
		}catch(Exception e) {
			System.out.println(e);
		}*/
		

	}
}	
